name: 'Purge docker container github'
description: 'Purge docker container'
inputs:
  packageType:
    description: 'packageType'
    required: true
    default: 'container'
  packageName:
    description: 'packageName'
    required: true
  organisation:
    description: 'organisation'
    required: true
  token:
    description: 'token'
    required: true
  pagination:
    description: 'pagination'
    default: 100
  keepDays:
    description: 'how many days before eligible for deletion'
    default: 30
  dryRun:
    description: 'Dry run'
    default: false
  logLevel:
    description: 'Log level (trace, debug, info, warn, error)'
    default: 'info'
outputs:
  deleted:
    description: 'Versions selected for deletion'
  envList:
    description: 'List environnement with 1 outdated version kept'
runs:
  using: 'node12'
  main: 'dist/index.js'
