name: 'act-local-test'
on: workflow_dispatch

jobs:
  act-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "purge-docker-registry-action"
      - uses: ./
        with:
          packageName: yeap-modelisation-db
          organisation: yeapAi
          token: ${{ secrets.GITHUB_TOKEN }}
          dryRun: true
          logLevel: trace
          keepDays: 15
